#!/usr/bin/perl -w

# add: no webcache flag


use Getopt::Long;
use strict;

my($webcache, $jarfile, $default_jarfile, $default_webcache, $file, @files);


$default_webcache = "/var/daitss/webcache/";
$default_jarfile  = "/opt/daitss/lib/xmlvalidator.jar";


GetOptions("webcache=s" => \$webcache,
	   "jarfile=s"  => \$jarfile) or Usage();


$webcache ||= $default_webcache;
$jarfile  ||= $default_jarfile;


if (! -f $jarfile) {
  print STDERR "Jar file $jarfile does not exist.\n";
  Usage();
}

if (! -d $webcache) {
  print STDERR "Web cache directory $webcache does not exist.\n";
  Usage();
}

if (! -w $webcache) {
  print STDERR "Web cache directory $webcache is not writable.\n";
  Usage();
}


    
  

@files = @ARGV;

foreach $file (@files) {

  if (! -f $file) {
    print STDERR "File $file does not exist.\n";
    next;
  }

  print "java -Dwebcache=$webcache -Dfile=$file -jar $jarfile\n";
  print `java -Dwebcache="$webcache" -Dfile="$file" -jar "$jarfile"`
      
}


sub Usage {
  my ($me);

  $me = $0;   $me =~ s|^.*/||;

  print STDERR <<EOF;
Usage: $me [ --webcache <webcache directory: defaults to $default_webcache> ] [ --jarfile <jar file: defaults to $default_jarfile> ] file [.. files .. ]
EOF

  exit;
}
